/*
Jméno a pøíjmení: Kateøina Foøtová
Login: xforto00
Projekt: ARM-FITkit3: Mìøení srdeèního tepu
Pøedmìt: IMP
originál
Datum posledních zmìn v souboru:
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MK60DN512xxx10
package_id: MK60DN512VMD10
mcu_data: ksdk2_0
processor_version: 6.0.0
pin_labels:
- {pin_num: B9, pin_signal: PTD9/I2C0_SDA/UART5_TX/FB_A17, label: DISPLAY_FOURTH_NUM, identifier: DISPLAY_FOURTH_NUM}
- {pin_num: L1, pin_signal: PGA0_DP/ADC0_DP0/ADC1_DP3, label: HEARTBEAT_MODULE, identifier: HEARTBEAT_MODULE}
- {pin_num: C9, pin_signal: PTD8/I2C0_SCL/UART5_RX/FB_A16, label: DISPLAY_FIRST_NUM, identifier: DISPLAY_FIRST_NUM}
- {pin_num: B1, pin_signal: PTD12/SPI2_SCK/SDHC0_D4/FB_A20, label: DISPLAY_THIRD_NUM, identifier: DISPLAY_THIRD_NUM}
- {pin_num: C3, pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, label: DISPLAY_SECOND_NUM, identifier: DISPLAY_SECOND_NUM}
- {pin_num: C2, pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22, label: DISPLAY_SEGMENT_C, identifier: DISPLAY_SEGMENT_C}
- {pin_num: L9, pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB, label: DISPLAY_SEGMENT_A, identifier: DISPLAY_SEGMENT_A}
- {pin_num: L8, pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1, label: DISPLAY_SEGMENT_B, identifier: DISPLAY_SEGMENT_B}
- {pin_num: M9, pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0, label: DISPLAY_SEGMENT_D, identifier: DISPLAY_SEGMENT_D}
- {pin_num: J7, pin_signal: PTA6/FTM0_CH3/TRACE_CLKOUT, label: DISPLAY_SEGMENT_E, identifier: DISPLAY_SEGMENT_E}
- {pin_num: J8, pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3, label: DISPLAY_SEGMENT_F, identifier: DISPLAY_SEGMENT_F}
- {pin_num: C1, pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, label: DISPLAY_SEGMENT_G, identifier: DISPLAY_SEGMENT_G}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L1, peripheral: ADC0, signal: 'DP, 0', pin_signal: PGA0_DP/ADC0_DP0/ADC1_DP3}
  - {pin_num: C9, peripheral: GPIOD, signal: 'GPIO, 8', pin_signal: PTD8/I2C0_SCL/UART5_RX/FB_A16}
  - {pin_num: B9, peripheral: GPIOD, signal: 'GPIO, 9', pin_signal: PTD9/I2C0_SDA/UART5_TX/FB_A17}
  - {pin_num: B1, peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/SPI2_SCK/SDHC0_D4/FB_A20}
  - {pin_num: C3, peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21}
  - {pin_num: C2, peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/SPI2_SIN/SDHC0_D6/FB_A22}
  - {pin_num: C1, peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23}
  - {pin_num: M9, peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTA10/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TRACE_D0}
  - {pin_num: J7, peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM0_CH3/TRACE_CLKOUT}
  - {pin_num: L9, peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/FTM2_CH1/MII0_RXCLK/FTM2_QD_PHB}
  - {pin_num: J8, peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: ADC0_SE10/PTA7/FTM0_CH4/TRACE_D3}
  - {pin_num: L8, peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FTM1_CH1/MII0_RXD3/FTM1_QD_PHB/TRACE_D1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t DISPLAY_SEGMENT_D_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin M9)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_D_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_D_PIN, &DISPLAY_SEGMENT_D_config);

    gpio_pin_config_t DISPLAY_SEGMENT_A_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA11 (pin L9)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_A_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_A_PIN, &DISPLAY_SEGMENT_A_config);

    gpio_pin_config_t DISPLAY_SEGMENT_E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin J7)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_E_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_E_PIN, &DISPLAY_SEGMENT_E_config);

    gpio_pin_config_t DISPLAY_SEGMENT_F_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA7 (pin J8)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_F_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_F_PIN, &DISPLAY_SEGMENT_F_config);

    gpio_pin_config_t DISPLAY_SEGMENT_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin L8)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_B_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_B_PIN, &DISPLAY_SEGMENT_B_config);

    gpio_pin_config_t DISPLAY_THIRD_NUM_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD12 (pin B1)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_THIRD_NUM_GPIO, BOARD_INITPINS_DISPLAY_THIRD_NUM_PIN, &DISPLAY_THIRD_NUM_config);

    gpio_pin_config_t DISPLAY_SECOND_NUM_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD13 (pin C3)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SECOND_NUM_GPIO, BOARD_INITPINS_DISPLAY_SECOND_NUM_PIN, &DISPLAY_SECOND_NUM_config);

    gpio_pin_config_t DISPLAY_SEGMENT_C_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD14 (pin C2)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_C_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_C_PIN, &DISPLAY_SEGMENT_C_config);

    gpio_pin_config_t DISPLAY_SEGMENT_G_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin C1)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_SEGMENT_G_GPIO, BOARD_INITPINS_DISPLAY_SEGMENT_G_PIN, &DISPLAY_SEGMENT_G_config);

    gpio_pin_config_t DISPLAY_FIRST_NUM_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD8 (pin C9)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_FIRST_NUM_GPIO, BOARD_INITPINS_DISPLAY_FIRST_NUM_PIN, &DISPLAY_FIRST_NUM_config);

    gpio_pin_config_t DISPLAY_FOURTH_NUM_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD9 (pin B9)  */
    GPIO_PinInit(BOARD_INITPINS_DISPLAY_FOURTH_NUM_GPIO, BOARD_INITPINS_DISPLAY_FOURTH_NUM_PIN, &DISPLAY_FOURTH_NUM_config);

    /* PORTA10 (pin M9) is configured as PTA10 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_D_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_D_PIN, kPORT_MuxAsGpio);

    /* PORTA11 (pin L9) is configured as PTA11 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_A_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_A_PIN, kPORT_MuxAsGpio);

    /* PORTA6 (pin J7) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_E_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_E_PIN, kPORT_MuxAsGpio);

    /* PORTA7 (pin J8) is configured as PTA7 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_F_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_F_PIN, kPORT_MuxAsGpio);

    /* PORTA9 (pin L8) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_B_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_B_PIN, kPORT_MuxAsGpio);

    /* PORTD12 (pin B1) is configured as PTD12 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_THIRD_NUM_PORT, BOARD_INITPINS_DISPLAY_THIRD_NUM_PIN, kPORT_MuxAsGpio);

    /* PORTD13 (pin C3) is configured as PTD13 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SECOND_NUM_PORT, BOARD_INITPINS_DISPLAY_SECOND_NUM_PIN, kPORT_MuxAsGpio);

    /* PORTD14 (pin C2) is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_C_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_C_PIN, kPORT_MuxAsGpio);

    /* PORTD15 (pin C1) is configured as PTD15 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_SEGMENT_G_PORT, BOARD_INITPINS_DISPLAY_SEGMENT_G_PIN, kPORT_MuxAsGpio);

    /* PORTD8 (pin C9) is configured as PTD8 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_FIRST_NUM_PORT, BOARD_INITPINS_DISPLAY_FIRST_NUM_PIN, kPORT_MuxAsGpio);

    /* PORTD9 (pin B9) is configured as PTD9 */
    PORT_SetPinMux(BOARD_INITPINS_DISPLAY_FOURTH_NUM_PORT, BOARD_INITPINS_DISPLAY_FOURTH_NUM_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
