/*
Jmeno a prijmeni: Katerina Fortova
Login: xforto00
Projekt: ARM-FITkit3: Mereni srdecniho tepu
Predmet: IMP
original
Datum poslednich zmen v souboru: 17. prosince 2019
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name ADC0_DP0 (coord L1), HEARTBEAT_MODULE
  @{ */
/* @} */

/*! @name PORTD8 (coord C9), DISPLAY_FIRST_NUM
  @{ */
#define BOARD_INITPINS_DISPLAY_FIRST_NUM_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_FIRST_NUM_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_FIRST_NUM_PIN 8U     /*!<@brief PORTD pin index: 8 */
                                                    /* @} */

/*! @name PORTD9 (coord B9), DISPLAY_FOURTH_NUM
  @{ */
#define BOARD_INITPINS_DISPLAY_FOURTH_NUM_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_FOURTH_NUM_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_FOURTH_NUM_PIN 9U     /*!<@brief PORTD pin index: 9 */
                                                     /* @} */

/*! @name PORTD12 (coord B1), DISPLAY_THIRD_NUM
  @{ */
#define BOARD_INITPINS_DISPLAY_THIRD_NUM_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_THIRD_NUM_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_THIRD_NUM_PIN 12U    /*!<@brief PORTD pin index: 12 */
                                                    /* @} */

/*! @name PORTD13 (coord C3), DISPLAY_SECOND_NUM
  @{ */
#define BOARD_INITPINS_DISPLAY_SECOND_NUM_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_SECOND_NUM_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_SECOND_NUM_PIN 13U    /*!<@brief PORTD pin index: 13 */
                                                     /* @} */

/*! @name PORTD14 (coord C2), DISPLAY_SEGMENT_C
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_C_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_SEGMENT_C_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_SEGMENT_C_PIN 14U    /*!<@brief PORTD pin index: 14 */
                                                    /* @} */

/*! @name PORTD15 (coord C1), DISPLAY_SEGMENT_G
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_G_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DISPLAY_SEGMENT_G_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DISPLAY_SEGMENT_G_PIN 15U    /*!<@brief PORTD pin index: 15 */
                                                    /* @} */

/*! @name PORTA10 (coord M9), DISPLAY_SEGMENT_D
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_D_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_D_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_D_PIN 10U    /*!<@brief PORTA pin index: 10 */
                                                    /* @} */

/*! @name PORTA6 (coord J7), DISPLAY_SEGMENT_E
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_E_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_E_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_E_PIN 6U     /*!<@brief PORTA pin index: 6 */
                                                    /* @} */

/*! @name PORTA11 (coord L9), DISPLAY_SEGMENT_A
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_A_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_A_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_A_PIN 11U    /*!<@brief PORTA pin index: 11 */
                                                    /* @} */

/*! @name PORTA7 (coord J8), DISPLAY_SEGMENT_F
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_F_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_F_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_F_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                                    /* @} */

/*! @name PORTA9 (coord L8), DISPLAY_SEGMENT_B
  @{ */
#define BOARD_INITPINS_DISPLAY_SEGMENT_B_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_B_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DISPLAY_SEGMENT_B_PIN 9U     /*!<@brief PORTA pin index: 9 */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
